### ISSUE TITLE
Exception when calling a 'brackets done loading' handler: TypeError: number is not a function

### ISSUE THREAD

**Issue by alvint** [dnbard/extensions-toolbar#16]
The error may (or may not) be triggered by `main.js` line 49. This appears to somehow interfere with the proper display of subsequent errors in other plugins.

**Comment by alvint** [comment]
![screen shot 2015-02-06 at 12 52 36 pm](https://cloud.githubusercontent.com/assets/622202/6084437/1495a950-adff-11e4-8f67-6817948300c1.png)

**Comment by dnbard** [comment]
Thanks, fixed in 0046e8817160259fd2d89fd262abca115012167d

**Comment by alvint** [comment]
Fast!
