### ISSUE TITLE
Extension bar stays in the same position

### ISSUE THREAD

**Issue by Shakil-Shahadat** [dnbard/extensions-toolbar#17]
Please see the attached picture.

![image](https://cloud.githubusercontent.com/assets/8978625/8890772/31f7e008-332e-11e5-968f-efe6a3213de9.png)

**Comment by dnbard** [comment]
Is there some errors in the developers tools? 
Also, did you try to reproduce this issue with only *this* extension installed?

**Comment by Shakil-Shahadat** [comment]
No there was no error due to this plugin. I checked by uninstalling all my plugins one by one. It seems there was a conflict with the 'W3CValidation' plugin. Uninstalling that plugin solved the problem. Although I reinstalled the plugin, I don't see the bar anymore.

Closing the issue for now. I will reopen it if I see it again.

Thanks for your attention and for the plugin.
